name: build & deploy
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            git clone git@github.com:0JAFC0/0jafc0.backend.git
            docker compose down
            docker compose up --build
            echo 'Deployment sucessfull to digital ocean'
